import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header/Header";
import { CartProvider } from "@/context/CartContext";
import { getCartAction } from "./(cart)/getCart/action";
import { CartSlider } from "@/components/CartSlider/CartSlider";

const interFont = Inter({
  variable: "--font-google",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cart = await getCartAction();

  if (!cart.success || !cart.data) {
    return <p>Failed to get cart...</p>;
  }

  return (
    <html lang="en">
      <body
        className={`${interFont.variable} font-sans antialiased bg-red-500`}
      >
        <CartProvider initialCart={cart.data}>
          <Header />
          <CartSlider />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
